name: Deploy react project
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"



jobs:
  build:
    name: Build phase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 14.0
      - uses: actions/cache@v2.1.3
        with: 
          path: prime_numbers
          key: ${{ runner.os}}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os}}-node-


      - name: Build Deps
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm install --silent 


      - name: Compile app
        run: npm run build

       

